#Include %A_ScriptDir%\src\settings\settings_schema.ahk
#Include %A_ScriptDir%\src\app\app_lifecycle.ahk
#Include %A_ScriptDir%\src\app\record_identity.ahk
#Include %A_ScriptDir%\src\reactions\reaction_controller.ahk
#Include %A_ScriptDir%\src\ui\palette\palette_view.ahk
#Include %A_ScriptDir%\src\ui\management\management_view.ahk
#Include %A_ScriptDir%\src\ui\management\management_dialogs.ahk
#Include %A_ScriptDir%\src\ui\help_view.ahk
#Include %A_ScriptDir%\src\ui\reaction_feedback.ahk
#Include %A_ScriptDir%\src\ui\ui_runtime.ahk
#Include %A_ScriptDir%\src\ui\window_presenter.ahk
#Include %A_ScriptDir%\src\ui\diagnostics.ahk
#Include %A_ScriptDir%\src\ui\shortcut_manager.ahk
#Include %A_ScriptDir%\src\shortcuts\shortcut_controller.ahk
#Include %A_ScriptDir%\src\shortcuts\shortcut_policy.ahk
#Include %A_ScriptDir%\src\shortcuts\shortcut_bindings.ahk
#Include %A_ScriptDir%\src\ui\palette\palette_controller.ahk
#Include %A_ScriptDir%\src\browser\browser_service.ahk
#Include %A_ScriptDir%\src\browser\reaction_registration_service.ahk
#Include %A_ScriptDir%\src\ui\panel_viewport.ahk
#Include %A_ScriptDir%\src\library\danmaku_library.ahk
#Include %A_ScriptDir%\src\storage\sqlite_connection.ahk
#Include %A_ScriptDir%\src\settings\settings_validation.ahk
#Include %A_ScriptDir%\src\settings\library_storage_plan.ahk
#Include %A_ScriptDir%\src\settings\reaction_registration_repository.ahk
#Include %A_ScriptDir%\src\settings\shortcut_repository.ahk
#Include %A_ScriptDir%\src\settings\settings_repository.ahk
#Include %A_ScriptDir%\src\settings\settings_store.ahk
#Include %A_ScriptDir%\src\browser\worker_client.ahk
#Include %A_ScriptDir%\src\input\text_input.ahk
#Include %A_ScriptDir%\src\input\input_controller.ahk
#Include %A_ScriptDir%\src\settings\settings_service.ahk
#Include %A_ScriptDir%\src\library\profile_service.ahk
#Include %A_ScriptDir%\src\library\library_service.ahk
#Include %A_ScriptDir%\src\ui\management\management_controller.ahk
#Include %A_ScriptDir%\src\app\runtime_ports.ahk
#Include %A_ScriptDir%\src\app\source_status.ahk
#Include %A_ScriptDir%\src\app\app_startup.ahk
#Include %A_ScriptDir%\src\app\operation_policy.ahk
#Include %A_ScriptDir%\src\ui\library_presentation.ahk
#Include %A_ScriptDir%\src\ui\refresh_cycle.ahk
#Include %A_ScriptDir%\src\ui\browser_feedback.ahk
#Include %A_ScriptDir%\src\shortcuts\focused_input.ahk
